# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KUAIXIAO_Swift' do
	pod 'SwiftyJSON'
	pod 'ReachabilitySwift'
	pod 'FillableLoaders', '~>1.3.0'
	pod 'RAMAnimatedTabBarController', "~> 2.0.13"
	pod 'Alamofire', '~> 4.5'
	pod 'DZNEmptyDataSet'
	pod 'Onboard'
	pod 'SJProgressHUD'
        pod 'WHC_Layout'
	pod 'SexyJson'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KUAIXIAO_Swift

  target 'KUAIXIAO_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KUAIXIAO_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
